name: Node.js Setup and Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          npm install moment simple-git random jsonfile

      - name: Configure Git
        run: |
          git config --global user.name "fahri1616"
          git config --global user.email "ClearenceLaposky101899@outlook.com"

      - name: Run Node.js script
        run: |
          node index.js

      - name: Push changes to main
        run: |
          git push -f origin main
